# Use the specified base image
# FROM wengkd/jetson:r35.4-ml-ros2
FROM wengkd/jetson:r35.4-torch-ros2

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH=/usr/local/bin:$PATH

# ================= Basic System Setup ======================
# Update the system and install essential tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    wget \
    git \
    vim nano \
    ca-certificates \
    libssl-dev \
    libffi-dev \
    tmux \
    sudo \
    usbutils \
    bash-completion \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


# ================= Custom User Setup ======================
# Create a non-root user 'work'
RUN useradd -ms /bin/bash work

# # Grant sudo privileges to the 'work' user
RUN echo "work ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# # Set a custom hostname
RUN echo "aa" > /etc/hostname

# # Set the working directory and give permissions to the 'work' user
RUN mkdir -p /workspace && chown work:work /workspace
WORKDIR /workspace


# ================= Custom Shell Environment ======================
# Customize PS1 prompt to make it more noticeable
RUN echo "PS1='\[\033[1;31m\]\u@\[\033[1;34m\]\h\[\033[0m\]:\[\033[1;33m\]\w\[\033[0m\]\$ '" >> /home/work/.bashrc

# # Enable bash-completion
RUN echo "source /usr/share/bash-completion/bash_completion" >> /home/work/.bashrc

# Switch to root user temporarily for install tool
USER root



# ================= Install Image Tool ======================
# RUN apt-get remove -y python3-sympy
RUN pip install matplotlib==3.7.5 tqdm
RUN pip install --no-deps ultralytics


# ================= Camera Tool ======================
RUN apt-get update && apt-get install -y --no-install-recommends \
    v4l-utils \
    ffmpeg \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


# ================= Other Tool ======================
RUN pip install dynamixel_sdk       # Dynamixel Motor



# ================= ROS2 Setup ======================
# Source ROS2 environment on startup
RUN echo "source /opt/ros/humble/install/setup.bash" >> /home/work/.bashrc
# Localhost-Only Communication
RUN echo "export ROS_LOCALHOST_ONLY=1" >> /home/work/.bashrc
# Set Domain ID
# RUN echo "export ROS_DOMAIN_ID=11" >> /home/work/.bashrc




# # ================= Copy tmux Configuration ======================
# # Copy tmux.conf to root and work user directories
# COPY tmux.conf /root/.tmux.conf
# COPY tmux.conf /home/work/.tmux.conf

# # Enable tmux to start automatically for both root and work users
# # RUN echo '[ -z "$TMUX" ] && tmux' >> /home/work/.bashrc
# RUN echo "if command -v tmux &> /dev/null; then" >> /home/work/.bashrc && \
#     echo "  tmux ls &> /dev/null || true" >> /home/work/.bashrc && \
#     echo "fi" >> /home/work/.bashrc

# ================= Finalize Container Configuration ======================
# Switch back to non-root user
RUN usermod -aG video work
USER work

RUN sudo apt-get install -y libopencv-calib3d-dev
RUN pip3 install opencv-contrib-python
RUN pip3 install torchvision

# Default container startup command (modify as needed)
CMD ["bash"]
